package com.example.lynnyuki.cloudfunny.model.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.lynnyuki.cloudfunny.model.bean.ImageBean;
import com.example.lynnyuki.cloudfunny.model.bean.LikeBean;

import com.example.lynnyuki.cloudfunny.model.db.ImageBeanDao;
import com.example.lynnyuki.cloudfunny.model.db.LikeBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig imageBeanDaoConfig;
    private final DaoConfig likeBeanDaoConfig;

    private final ImageBeanDao imageBeanDao;
    private final LikeBeanDao likeBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        imageBeanDaoConfig = daoConfigMap.get(ImageBeanDao.class).clone();
        imageBeanDaoConfig.initIdentityScope(type);

        likeBeanDaoConfig = daoConfigMap.get(LikeBeanDao.class).clone();
        likeBeanDaoConfig.initIdentityScope(type);

        imageBeanDao = new ImageBeanDao(imageBeanDaoConfig, this);
        likeBeanDao = new LikeBeanDao(likeBeanDaoConfig, this);

        registerDao(ImageBean.class, imageBeanDao);
        registerDao(LikeBean.class, likeBeanDao);
    }
    
    public void clear() {
        imageBeanDaoConfig.clearIdentityScope();
        likeBeanDaoConfig.clearIdentityScope();
    }

    public ImageBeanDao getImageBeanDao() {
        return imageBeanDao;
    }

    public LikeBeanDao getLikeBeanDao() {
        return likeBeanDao;
    }

}
